import pandas as pd
import numpy as np
import os
import sys

# Replicate Strategy V4 logic
def test_gap_logic():
    data_path = 'c:\\Trading\\temp_combined_data.csv' # Use the temp file generated by comparison script
    if not os.path.exists(data_path):
        print(f"File not found: {data_path}")
        return

    print(f"Loading {data_path}...")
    df = pd.read_csv(data_path, index_col=0, parse_dates=True)
    df.columns = ['open', 'high', 'low', 'close', 'volume']
    
    print(f"Original Length: {len(df)}")
    
    # SCAN ORIGINAL FOR GAPS (Input Data)
    print("\nScanning ORIGINAL DATA for Time Gaps > 2 minutes...")
    diffs = df.index.to_series().diff()
    orig_gaps = diffs[diffs > pd.Timedelta(minutes=2)]
    
    if not orig_gaps.empty:
         print(f"FOUND {len(orig_gaps)} GAPS IN ORIGINAL:")
         print(orig_gaps.sort_values(ascending=False).head(10))
    else:
         print("NO GAPS IN ORIGINAL DATA.")

    # Check for NaNs in Input
    nan_rows = df[df.isnull().any(axis=1)]
    if not nan_rows.empty:
         print(f"FOUND NANS IN INPUT DATA: {len(nan_rows)} rows")
         print(nan_rows)
    else:
         print("No NaNs in Input Data.")
         
    # ... (rest of script can terminate or continue)
    pass
    
    # Check Gap in Original
    df_jan = df[df.index >= '2026-01-15'] # Optimization: just jan 15
    print(f"Jan 15 Data Head (Original):")
    print(df_jan.head(5))
    
    # Resample
    timeframe = 2
    print(f"\nResampling {timeframe}T...")
    df_resampled = df.resample(f'{timeframe}T', label='right', closed='left').agg({
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum'
    })
    
    print(f"Resampled Length (Before Drop): {len(df_resampled)}")
    
    # DEEP INSPECT 09:12 (Original & Resampled)
    print("\n[DEBUG AGGREGATION]")
    print("ORIGINAL (1-min) 09:10-09:14:")
    mask_orig = (df.index >= '2026-01-15 09:10') & (df.index <= '2026-01-15 09:14')
    print(df.loc[mask_orig])
    
    print("RESAMPLED (2-min) 09:10-09:14:")
    mask_res = (df_resampled.index >= '2026-01-15 09:10') & (df_resampled.index <= '2026-01-15 09:14')
    print(df_resampled.loc[mask_res])

    # SCAN FOR GAPS > 2 MIN
    print("\nScanning for Time Gaps > 2 minutes...")
    time_diffs = df_resampled.index.to_series().diff()
    gaps = time_diffs[time_diffs > pd.Timedelta(minutes=2)]
    
    if not gaps.empty:
         print(f"FOUND {len(gaps)} GAPS:")
         print(gaps.sort_values(ascending=False).head(10))
    else:
         print("NO GAPS FOUND (Continuous 2-min Data).")
         
    # Check specific Jan 06 -> Jan 15 transition if relevant
    # ...
            
    # DEEP INSPECT 09:12
    chk_mask = df.index.astype(str).str.startswith('2026-01-15 09:12')
    if chk_mask.any():
         print("\n[DEBUG GAP] Jan 15 09:12 Data (Backtest):")
         print(df.loc[chk_mask])
    else:
         print("\n[DEBUG GAP] Jan 15 09:12 NOT FOUND in Resampled Data.")

    # Apply Fix
    print("\nApplying dropna(how='any')...")
    df_fixed = df_resampled.dropna(subset=['open', 'high', 'low', 'close', 'volume'], how='any')
    
    print(f"Fixed Length: {len(df_fixed)}")
    
    # Inspect Transition
    if last_jan6 and first_jan15:
        # Find index location of last_jan6
        try:
            loc = df_fixed.index.get_loc(last_jan6)
            print(f"Row at Last Jan 6: {df_fixed.iloc[loc]}")
            print(f"Row after (Next Adjacency): {df_fixed.iloc[loc+1]}")
            
            diff = df_fixed.index[loc+1] - df_fixed.index[loc]
            print(f"Time Delta: {diff}")
        except Exception as e:
            print(f"Error inspecting transition: {e}")
            # maybe last_jan6 was dropped?
            
            print(f"Time Delta: {diff}")
        except Exception as e:
            print(f"Error inspecting transition: {e}")
            
    # ...
    
    # Check ADX Calc
    print("\nChecking ADX Calculation (Exact Replica)...")
    def calculate_adx_replica(df, length):
        high = df['high']
        low = df['low']
        close = df['close']
        
        tr1 = high - low
        tr2 = abs(high - close.shift(1))
        tr3 = abs(low - close.shift(1))
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        
        up = high - high.shift(1)
        down = low.shift(1) - low
        
        plus_dm = np.where((up > down) & (up > 0), up, 0.0)
        minus_dm = np.where((down > up) & (down > 0), down, 0.0)
        
        plus_dm = pd.Series(plus_dm, index=df.index)
        minus_dm = pd.Series(minus_dm, index=df.index)
        
        atr = tr.ewm(alpha=1/length, adjust=False).mean()
        plus_di = 100 * (plus_dm.ewm(alpha=1/length, adjust=False).mean() / atr)
        minus_di = 100 * (minus_dm.ewm(alpha=1/length, adjust=False).mean() / atr)
        
        sum_di = plus_di + minus_di
        dx = 100 * (abs(plus_di - minus_di) / sum_di)
        dx = dx.fillna(0)
        
        adx = dx.ewm(alpha=1/length, adjust=False).mean()
        return adx

    adx_period = 20 # From parameters
    df['adx'] = calculate_adx_replica(df, adx_period)
    
    # Check 09:12 presence
    ts_target = pd.Timestamp("2026-01-15 09:12:00")
    if ts_target in df.index:
         val = df.loc[ts_target, 'atr_ts']
         adx_val = df.loc[ts_target, 'adx']
         print(f"09:12 ATR (56): {val}")
         print(f"09:12 ADX (20): {adx_val}")
    else:
         print("09:12 NOT FOUND in Fixed DF!")

if __name__ == "__main__":
    test_gap_logic()
